# Generated by Django 5.2.6 on 2025-09-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_caste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caste',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='home.caste'),
        ),
    ]
